services:
  base: # dummy service for building base image
    image: maly_woz/base:jazzy
    build:
      dockerfile: docker/base/Dockerfile
      context: .
    deploy:
      replicas: 0

  software:
    image: maly_woz/software:jazzy
    build:
      dockerfile: docker/software/Dockerfile
      context: .
    depends_on:
      - base
    container_name: software
    network_mode: host
    ipc: host
    shm_size: 512m
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
      # X11 for GUI
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Workspace mount
      - ./:/workspace:cached
      # Colcon build/install/log volumes
      - colcon_build:/workspace/build
      - colcon_install:/workspace/install
      - colcon_log:/workspace/log
    stdin_open: true
    tty: true

  hardware:
    image: maly_woz/hardware:jazzy
    build:
      dockerfile: docker/hardware/Dockerfile
      context: .
    depends_on:
      - base
    container_name: hardware
    network_mode: host
    volumes:
      - ./:/workspace:cached
      - /dev:/dev
      - colcon_build:/workspace/build
      - colcon_install:/workspace/install
      - colcon_log:/workspace/log
    stdin_open: true
    tty: true

  simulation-nvidia:
    image: maly_woz/sim:jazzy
    build:
      dockerfile: docker/sim/Dockerfile
      context: .
    container_name: simulation
    network_mode: host
    ipc: host
    shm_size: 512m
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/workspace:cached
      - colcon_build:/workspace/build
      - colcon_install:/workspace/install
      - colcon_log:/workspace/log
    stdin_open: true
    tty: true

  simulation-intel-amd:
    image: maly_woz/sim:jazzy
    build:
      dockerfile: docker/sim/Dockerfile
      context: .
    container_name: simulation
    network_mode: host
    ipc: host
    shm_size: 512m
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/workspace:cached
      - /dev/dri:/dev/dri
      - colcon_build:/workspace/build
      - colcon_install:/workspace/install
      - colcon_log:/workspace/log
    stdin_open: true
    tty: true

volumes:
  colcon_build:
  colcon_install:
  colcon_log:
