<?xml version="1.0"?>
<robot name="maly_woz" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find maly_woz_description)/urdf/leg.urdf.xacro" />
  <xacro:include filename="$(find maly_woz_description)/urdf/materials.urdf.xacro" />
  <xacro:include filename="$(find maly_woz_description)/urdf/inertia.urdf.xacro" />
  <xacro:include filename="$(find maly_woz_description)/urdf/sensors/realsense_d435/realsense_d435.urdf.xacro" />

  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="leg_length" value="0.2"/>
  <xacro:property name="chassis_length" value="0.8"/>
  <xacro:property name="chassis_width" value="0.5"/>

  <link name="base_link" />

  <link name="body">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} 0.3"/>
      </geometry>
      <material name="blue" />
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} 0.3"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="3.0"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <xacro:solid_cuboid_inertia m="3.0" w="${chassis_width}" d="${chassis_length}" h="0.3" />
    </inertial>
  </link>

  <joint name="body_joint" type="fixed">
    <parent link="base_link"/>
    <child link="body"/>
    <origin xyz="0 0 ${wheel_radius + leg_length}" rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
  </joint>

  <xacro:leg suffix="front_left" parent="body" front="1" left="1"
             x_offset="${chassis_length / 2}" y_offset="${chassis_width / 2}" z_offset="0.0"
             wheel_radius="${wheel_radius}" leg_length="${leg_length}" />

  <xacro:leg suffix="front_right" parent="body" front="1" left="-1"
             x_offset="${chassis_length / 2}" y_offset="-${chassis_width / 2}" z_offset="0.0"
             wheel_radius="${wheel_radius}" leg_length="${leg_length}" />

  <xacro:leg suffix="rear_left" parent="body" front="-1" left="1"
             x_offset="-${chassis_length / 2}" y_offset="${chassis_width / 2}" z_offset="0.0"
             wheel_radius="${wheel_radius}" leg_length="${leg_length}" />

  <xacro:leg suffix="rear_right" parent="body" front="-1" left="-1"
             x_offset="-${chassis_length / 2}" y_offset="-${chassis_width / 2}" z_offset="0.0"
             wheel_radius="${wheel_radius}" leg_length="${leg_length}" />

  <xacro:realsense_d435 prefix="realsense_front" parent="body">
    <origin xyz="0.4 0 0.2" rpy="0 ${20 * pi / 180} 0"/>
  </xacro:realsense_d435>

  <gazebo>
    <plugin
      filename="gz-sim-diff-drive-system"
      name="gz::sim::systems::DiffDrive">
      <left_joint>wheel_front_left_joint</left_joint>
      <left_joint>wheel_rear_left_joint</left_joint>
      <right_joint>wheel_front_right_joint</right_joint>
      <right_joint>wheel_rear_right_joint</right_joint>
      <wheel_separation>${1.0 + 2 * 0.05 + 0.05}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <odom_publish_frequency>30</odom_publish_frequency>
      <max_linear_acceleration>5</max_linear_acceleration>
      <min_linear_acceleration>-5</min_linear_acceleration>
      <max_angular_acceleration>5</max_angular_acceleration>
      <min_angular_acceleration>-5</min_angular_acceleration>
      <max_linear_velocity>2.0</max_linear_velocity>
      <min_linear_velocity>-2.0</min_linear_velocity>
      <max_angular_velocity>2</max_angular_velocity>
      <min_angular_velocity>-2</min_angular_velocity>
      <frame_id>odom</frame_id>
      <child_frame_id>base_link</child_frame_id>
    </plugin>

    <plugin
      filename="gz-sim-joint-state-publisher-system"
      name="gz::sim::systems::JointStatePublisher">
    </plugin>
  </gazebo>
</robot>
