<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="leg" params="suffix parent front left x_offset y_offset z_offset">
    <link name="leg_${suffix}">
      <visual>
        <geometry>
          <box size="0.5 0.1 0.1"/>
        </geometry>
        <material name="blue" />
        <origin xyz="0.25 0 0" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <box size="0.5 0.2 0.2"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.3"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <xacro:solid_cuboid_inertia m="0.3" w="0.5" d="0.2" h="0.2" />
      </inertial>
    </link>

    <joint name="leg_${suffix}_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="leg_${suffix}"/>
      <origin
        xyz="${x_offset} ${y_offset + left * 0.05} ${z_offset}"
        rpy="0 ${(pi / 2) - (front * pi * 20 / 180)} 0"
      />
      <axis xyz="0 0 1"/>
    </joint>

    <link name="wheel_${suffix}">
      <visual>
        <geometry>
          <cylinder radius="0.1" length="0.1"/>
        </geometry>
        <material name="black" />
        <origin xyz="0 0 ${left * 0.05}" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="0.1" length="0.1"/>
        </geometry>
        <surface>
          <!-- TODO there is probably some bug with friction, we can't turn really well -->
          <friction>
            <ode>
              <mu>1</mu>
              <mu2>0.1</mu2>
              <slip1>0.035</slip1>
              <slip2>0</slip2>
              <fdir1>0 0 1</fdir1>
            </ode>
            <bullet>
              <friction>1</friction>
              <friction2>0.1</friction2>
              <rolling_friction>0.1</rolling_friction>
              <spinning_friction>0.1</spinning_friction>
            </bullet>
          </friction>
        </surface>
        <origin xyz="0 0 0.05" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.3"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <xacro:solid_cylinder_inertia m="0.1" r="0.1" h="0.1" />
      </inertial>
    </link>

    <joint name="wheel_${suffix}_joint" type="revolute">
      <parent link="leg_${suffix}"/>
      <child link="wheel_${suffix}"/>
      <origin xyz="0.5 ${left * 0.05} 0" rpy="${-pi / 2} 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="1000.0" lower="-1e300" upper="1e300" velocity="1e300"/>
    </joint>
  </xacro:macro>
</robot>
