<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="leg" params="suffix parent front left x_offset y_offset z_offset
                                  wheel_radius leg_length">
    <link name="leg_${suffix}">
      <visual>
        <geometry>
          <box size="${leg_length} 0.1 0.1"/>
        </geometry>
        <material name="blue" />
        <origin xyz="${leg_length / 2} 0 0" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <box size="${leg_length} 0.2 0.2"/>
        </geometry>
        <origin xyz="${leg_length / 2} 0 0" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.3"/>
        <origin xyz="${leg_length / 2} 0 0" rpy="0 0 0"/>
        <xacro:solid_cuboid_inertia m="0.3" w="${leg_length}" d="0.2" h="0.2" />
      </inertial>
    </link>

    <joint name="leg_${suffix}_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="leg_${suffix}"/>
      <origin
        xyz="${x_offset} ${y_offset + left * 0.05} ${z_offset}"
        rpy="0 ${pi / 2} 0"
      />
      <axis xyz="0 0 1"/>
    </joint>

    <link name="wheel_${suffix}">
      <visual>
        <geometry>
          <!-- <cylinder radius="${wheel_radius}" length="0.1"/> -->
          <sphere radius="${wheel_radius}"/>
        </geometry>
        <material name="black" />
        <origin xyz="0 0 ${left * 0.05}" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <!-- <cylinder radius="${wheel_radius}" length="0.1"/> -->
          <sphere radius="${wheel_radius}"/>
        </geometry>
        <origin xyz="0 0 ${left * 0.05}" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <xacro:solid_cylinder_inertia m="0.1" r="${wheel_radius}" h="0.1" />
        <origin xyz="0 0 ${left * 0.05}" rpy="0 0 0"/>
      </inertial>
    </link>

    <gazebo reference="wheel_${suffix}">
      <collision>
        <pose>0 0 ${left * 0.05} 0 0 0</pose>
        <surface>
          <friction>
            <ode>
              <mu>0.5</mu>
              <mu2>1.0</mu2>
              <fdir1>0 0 1</fdir1>
            </ode>
            <bullet>
              <friction>1</friction>
              <friction2>1</friction2>
              <rolling_friction>0.1</rolling_friction>
            </bullet>
            <!-- <ode>
              <mu>1.0</mu>
              <mu2>0.99</mu2>
              <slip1>0</slip1>
              <slip2>0.01</slip2>
              <fdir1>1 0 0</fdir1>
            </ode> -->
          </friction>
        </surface>
      </collision>
    </gazebo>

    <joint name="wheel_${suffix}_joint" type="revolute">
      <parent link="leg_${suffix}"/>
      <child link="wheel_${suffix}"/>
      <origin xyz="${leg_length} ${left * 0.05} 0" rpy="${-pi / 2} 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="1000.0" lower="-1e300" upper="1e300" velocity="1e300"/>
      <dynamics damping="0.0" friction="0.0"/>
      <joint_properties damping="0.0" friction="0.0"/>
    </joint>
  </xacro:macro>
</robot>
