- topic_name: "/clock"
  gz_type_name: "ignition.msgs.Clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  direction: GZ_TO_ROS

- topic_name: "/model/rover/cmd_vel"
  gz_type_name: "ignition.msgs.Twist"
  ros_type_name: "geometry_msgs/msg/Twist"

- topic_name: "/model/rover/odometry"
  gz_type_name: "ignition.msgs.Odometry"
  ros_type_name: "nav_msgs/msg/Odometry"

- gz_topic_name: "/world/demo_world/model/rover/joint_state"
  ros_topic_name: "/joint_states"
  gz_type_name: "ignition.msgs.Model"
  ros_type_name: "sensor_msgs/msg/JointState"

- gz_topic_name: "/model/rover/tf"
  ros_topic_name: "/tf"
  gz_type_name: "ignition.msgs.Pose_V"
  ros_type_name: "tf2_msgs/msg/TFMessage"

- topic_name: "/camera_front/image_raw"
  gz_type_name: "ignition.msgs.Image"
  ros_type_name: "sensor_msgs/msg/Image"

- topic_name: "/camera_front/camera_info"
  gz_type_name: "ignition.msgs.CameraInfo"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
